### PR TITLE
Add rwhnf

### LINKED ISSUE #3: Add `rwhnf` helper for NF=WHNF instances
Here's an idea for a helper I wanted to document:

``` haskell
-- | Reduce to weak head normal form
--
-- Useful for defining 'NFData' for types for which NF=WHNF holds.
--
-- > data T = C1 | C2 | C3
-- > instance NFData T where rnf = rwhnf
rwhnf :: a -> ()
rwhnf !_ = ()
```

### PR DESCRIPTION
**Pull request by phadej**
Resolve #3 

IMHO it's just easier to have it, even recent enough generics can get it right. Some people like being implicit (it would be cool if the assumption could be checked though).

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Now that we've got `rwhnf`, perhaps we should use it to cut out some boilerplate in the many `NFData` instance definitions in `Control.DeepSeq`? There's a [whole bunch of instances](https://github.com/phadej/deepseq/blob/2492fff7ca128fb20a7472a09d8fa0851ce9ada9/Control/DeepSeq.hs#L292) that are of the form `rnf !_ = ()` which we could replace with `rnf = rwhnf`.

**Comment by phadej** [comment]
can do if/when libraries@ discussion says this is ok to go in.

**Comment by RyanGlScott** [comment]
For reference, the libraries mailing list discussion is here: https://mail.haskell.org/pipermail/libraries/2016-October/027385.html

**Comment by RyanGlScott** [comment]
Three weeks have passed since the mailing list discussion opened, and there were no objections, so I say go ahead and make the changes in https://github.com/haskell/deepseq/pull/22#issuecomment-256110833. I can merge after that.

**Comment by phadej** [comment]
@RyanGlScott updated this.

**Pull request merged**
