### PR TITLE
Fix GHC version bound in CPP

### PR DESCRIPTION
**Pull request by sjakobi**
Context: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3388

### CODE REVIEW

**Comment by chessai** [comment]
We shouldn't have CPP referring to unstable branches of GHC in the source. So you should do the thing Ben mentioned in the other PR.

**Comment by sjakobi** [comment]
Well, since the current HEAD version is still `8.11.…`, my GHC MR can't validate without this patch. I have indeed pushed it to the GitLab mirror too, so maybe it's not necessary to merge it to master.

**Comment by chessai** [comment]
If it's in the GitLab mirror then your MR can validate, right?

**Comment by sjakobi** [comment]
> If it's in the GitLab mirror then your MR can validate, right?

Yep, it CI is green. If you've got a minute, could you possibly review it too? It's a `base` change, so core CLC territory. :)

**Comment by sjakobi** [comment]
FWIW, I wouldn't mind if this PR is closed. I'm just somewhat confused about the workflow of cross-submodule changes.

**Comment by chessai** [comment]
@sjakobi, OK, closing (which I planned to do anyway). Sorry, I know GHC's submodule usage is a bit weird.

**Comment by sjakobi** [comment]
Re-opening, based on the discussion in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3388#note_291686.

**Comment by sjakobi** [comment]
Re-pushed since there were some CI failures.

**Comment by sjakobi** [comment]
Ping @chessai.

**Comment by sjakobi** [comment]
Cheers! :)

**Pull request merged**
